<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
	'SubvitamineTools\Controller\CronController'                             => __DIR__ . '/src/SubvitamineTools/Crontroller/CronController.php',
	'SubvitamineTools\Module'                                                => __DIR__ . '/src/SubvitamineTools/Module.php'
);
